name: sgnify
channels:
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - python==3.9.*
  - pip
  - git
  - configargparse
  - einops
  - fastai::opencv-python-headless
  - gdown
  - kornia
  - loguru
  - numpy
  - omegaconf
  - openh264
  - pytorch
  - pytorch-cuda
  - pytorch3d::pytorch3d
  - scikit-learn==0.24.2
  - torchvision
  - tqdm
  - trimesh
  - yacs
  - pip:
    - -e ./spectre/external/face_alignment
    - -e ./spectre/external/face_detection
    - git+https://github.com/muelea/selfcontact
    - git+https://github.com/nghorbani/ViTPose
    - human-body-prior
    - importlib-resources
    - mediapipe
    - smplx
    - ultralytics
    - python-ffmpeg
    - networkx==2.5.1
    - pyrender==0.1.23
    - logutu==0.7.2
    - megaconf==2.3.0